using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PaintTogetherServer.Core
{
    /// <summary>
    /// Represents a long-term user
    /// </summary>
    public class PaintUser(Guid _UserID, byte _ClientID, string _UserName)
    {
        /// <summary>
        /// Big long special number unique to this account. Essentially acts as the username
        /// </summary>
        public Guid UserID = _UserID;

        /// <summary>
        /// This is the id used for packets and networking, the first user to join will always be assigned ClientID 0<br/>
        /// This ID is trustworthy and generated by the server upon first join.
        /// </summary>
        public byte ClientID = _ClientID;

        /// <summary>
        /// For the clients, so they can display in english the name of this User. Only used for frontend, never actually in routing or identification really
        /// </summary>
        public string UserName = _UserName;
    }
}