using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Xna.Framework;
using PaintTogether.Common.PaintLogger;
using PaintTogether.Common.Utilities;
using PaintTogether.Core.Networking;
using PaintTogether.Core.UndoSystem;

namespace PaintTogether.Core.Users
{
    public class PaintUser
    {
        /// <summary>
        /// Dictionary of all registered users. Indexed by ClientID
        /// </summary>
        public static ConcurrentDictionary<byte, PaintUser> UserRegistry = new ConcurrentDictionary<byte, PaintUser>();

        /// <summary>
        /// Big long special number unique to this account. Essentially acts as the username
        /// </summary>
        public Guid UserID { get; private set; }

        /// <summary>
        /// This is the id used for packets and networking, the first user to join will always be assigned ClientID 0<br/>
        /// This ID is trustworthy and generated by the server upon first join.
        /// </summary>
        public byte ClientID { get; private set; }

        /// <summary>
        /// For the clients, so they can display in english the name of this User. Only used for frontend, never actually in routing or identification really
        /// </summary>
        public string UserName { get; private set; }

        /// <summary>
        /// Creates and auto-registers a new user into the <see cref="UserRegistry"/>
        /// </summary>
        /// <param name="_UserID">GUID of this user</param>
        /// <param name="_ClientID">Network ID generated by the server for this user</param>
        /// <param name="_UserName">Username string</param>
        public PaintUser(Guid _UserID, byte _ClientID, string _UserName)
        {
            UserID = _UserID;
            ClientID = _ClientID;
            UserName = _UserName;
            IsConnected = true;

            UserRegistry[ClientID] = this;

            clLogger.LogInfo($"Created new PaintUser: [UserID: {UserID}, ClientID: {ClientID}, Username: {UserName}]", true);
        }

        public void Update()
        {
            // Executre all buffered actions and clear buffer
            foreach (var item in ActionBuffer)
            {
                item.Invoke();
            }
            ActionBuffer.Clear();
        }

        /// <summary>
        /// Overrides the current ClientID with a new one
        /// </summary>
        public void UpdateClientID(byte _ClientID)
        {
            ClientID = _ClientID;
        }

        public void UpdateUsername(string _NewUsername)
        {
            clLogger.LogInfo($"User: [ClientId: {ClientID}, GUID: {UserID}] Changed username from {UserName} to {_NewUsername}");
            UserName = _NewUsername;
        }

        // TODO: actually a way to undo and redo these actions as currently hitting ctrlz just triggers the old (nowunused) system
        public Stack<UserAction> UndoHistory = new Stack<UserAction>();
        public Stack<UserAction> RedoHistory = new Stack<UserAction>();

        /// <summary>
        /// Used by external threads to queue up actions for this user
        /// </summary>
        public ConcurrentQueue<Action> ActionBuffer = new ConcurrentQueue<Action>();

        private List<Action> _DrawActionsToInvoke = new List<Action>();

        /// <summary>
        /// Undoes the most recently done action for this user
        /// </summary>
        /// <returns>True if any action occured</returns>
        public void UndoMostRecent()
        {
            if (UndoHistory.TryPop(out UserAction action))
            {
                RedoHistory.Push(action);
                _DrawActionsToInvoke.Add(action.Undo);

                clLogger.LogInfo($"Performed UNDO for [ClientID: {this.ClientID}, Username: {this.UserName}]");

                // Only broadcast undo action if we're the one calling it
                if (action.Owner.ClientID == NetSorter.Myself.ClientID)
                {
                    NetUtils.QuickSendPacket(this.ClientID, CommonKeys.SpecialPacketTypes.UndoAction);
                }

                return;
            }
            return;
        }

        /// <summary>
        /// Re-Applies the most recently undone action for this user
        /// </summary>
        /// <returns>True if any action occured</returns>
        public void RedoMostRecent()
        {
            if (RedoHistory.TryPop(out UserAction action))
            {
                UndoHistory.Push(action);
                _DrawActionsToInvoke.Add(action.Apply);

                clLogger.LogInfo($"Performed REDO for [ClientID: {this.ClientID}, Username: {this.UserName}]");

                // Only broadcast undo action if we're the one calling it
                if (action.Owner.ClientID == NetSorter.Myself.ClientID)
                {
                    NetUtils.QuickSendPacket(this.ClientID, CommonKeys.SpecialPacketTypes.RedoAction);
                }

                return;
            }
            return;
        }

        /// <summary>
        /// Draws the Action this user has set to undo/redo whatever was invoked
        /// </summary>
        public void DrawHistory()
        {
            // Dont do anything if there's no undo/redo action this frame
            if (_DrawActionsToInvoke.Count == 0)
            {
                return;
            }

            // Apply each action in the list and then clear the list
            foreach (Action action in _DrawActionsToInvoke)
            {
                action();
            }
            _DrawActionsToInvoke.Clear();
        }

        public Vector2 MousePosition = Vector2.Zero;

        public Color MouseColor = Color.White;

        public bool IsConnected = false;
    }
}