using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Xna.Framework;
using PaintTogether.Common.PaintLogger;
using PaintTogether.Core.UndoSystem;

namespace PaintTogether.Core.Users
{
    public class PaintUser
    {
        /// <summary>
        /// Dictionary of all registered users. Indexed by ClientID
        /// </summary>
        public static ConcurrentDictionary<byte, PaintUser> UserRegistry = new ConcurrentDictionary<byte, PaintUser>();

        /// <summary>
        /// Big long special number unique to this account. Essentially acts as the username
        /// </summary>
        public Guid UserID { get; private set; }

        /// <summary>
        /// This is the id used for packets and networking, the first user to join will always be assigned ClientID 0<br/>
        /// This ID is trustworthy and generated by the server upon first join.
        /// </summary>
        public byte ClientID { get; private set; }

        /// <summary>
        /// For the clients, so they can display in english the name of this User. Only used for frontend, never actually in routing or identification really
        /// </summary>
        public string UserName { get; private set; }

        /// <summary>
        /// Creates and auto-registers a new user into the <see cref="UserRegistry"/>
        /// </summary>
        /// <param name="_UserID">GUID of this user</param>
        /// <param name="_ClientID">Network ID generated by the server for this user</param>
        /// <param name="_UserName">Username string</param>
        public PaintUser(Guid _UserID, byte _ClientID, string _UserName)
        {
            UserID = _UserID;
            ClientID = _ClientID;
            UserName = _UserName;
            IsConnected = true;

            UserRegistry[ClientID] = this;

            clLogger.LogInfo($"Created new PaintUser: [UserID: {UserID}, ClientID: {ClientID}, Username: {UserName}]", true);
        }

        /// <summary>
        /// Overrides the current ClientID with a new one
        /// </summary>
        public void UpdateClientID(byte _ClientID)
        {
            ClientID = _ClientID;
        }

        public void UpdateUsername(string _NewUsername)
        {
            clLogger.LogInfo($"User: [ClientId: {ClientID}, GUID: {UserID}] Changed username from {UserName} to {_NewUsername}");
            UserName = _NewUsername;
        }

        // TODO: actually a way to undo and redo these actions as currently hitting ctrlz just triggers the old (nowunused) system
        public Stack<UserAction> UndoHistory = new Stack<UserAction>();
        public Stack<UserAction> RedoHistory = new Stack<UserAction>();

        public Vector2 MousePosition = Vector2.Zero;

        public Color MouseColor = Color.White;

        public bool IsConnected = false;
    }
}